// Builds src/data/fontCatalog.js from the live Google Fonts metadata.
//
// Run with: node scripts/build-catalog.mjs
//
// Produces a flat list of serif/sans-serif families (excluding handwriting,
// monospace and symbol faces) with a baked-in visual class and a representative
// pair of weights. This catalog is what the pairing engine generates from, so
// the generator can draw on the entire Google Fonts library, not just the
// hand-curated pairings.

import { writeFileSync } from "fs";
import { curatedClass } from "../src/lib/substitutes.js";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const META_URL = "https://fonts.google.com/metadata/fonts";
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/data/fontCatalog.js");

// Coarse serif/sans-serif from the metadata's stroke (best signal), else
// category. Returns null when we can't tell (display/script without a stroke).
function coarseCategory(f) {
  const s = f.stroke;
  if (s === "Sans Serif") return "sans-serif";
  if (s === "Serif" || s === "Slab Serif") return "serif";
  if (f.category === "Serif") return "serif";
  if (f.category === "Sans Serif") return "sans-serif";
  return null;
}

// Fine visual class for the engine. Curated families keep their hand-tuned
// class; everything else is inferred from stroke + classifications + name.
function fineClass(f, coarse) {
  const curated = curatedClass(f.family);
  if (curated) return curated;
  const n = f.family.toLowerCase();
  const isDisplay = (f.classifications || []).includes("Display");
  if (coarse === "serif") {
    if (f.stroke === "Slab Serif" || /slab/.test(n)) return "slab";
    if (isDisplay || /playfair|didot|bodoni|didone/.test(n)) return "didone";
    return "old-style";
  }
  if (/condensed|narrow|compressed/.test(n)) return "condensed-sans";
  return "grotesque-sans";
}

// A representative [regular, bold] from the available static weights.
function pickWeights(f) {
  const numeric = Object.keys(f.fonts || {})
    .filter((k) => /^\d+$/.test(k))
    .map(Number)
    .sort((a, b) => a - b);
  if (!numeric.length) return null;
  const nearest = (t) => numeric.reduce((best, w) => (Math.abs(w - t) < Math.abs(best - t) ? w : best), numeric[0]);
  return [...new Set([nearest(400), nearest(700)])].sort((a, b) => a - b);
}

const EXCLUDE_CLASSIFICATIONS = new Set(["Handwriting", "Monospace", "Symbols"]);

const res = await fetch(META_URL);
const data = await res.json();
const list = data.familyMetadataList;

const catalog = [];
for (const f of list) {
  const cls = f.classifications || [];
  if (cls.some((c) => EXCLUDE_CLASSIFICATIONS.has(c))) continue;
  const category = coarseCategory(f);
  if (!category) continue;
  const weights = pickWeights(f);
  if (!weights) continue;
  catalog.push({ family: f.family, category, cls: fineClass(f, category), weights, pop: f.popularity ?? 99999 });
}

// Most popular first (nicer to read; sampling is uniform regardless).
catalog.sort((a, b) => a.pop - b.pop);

const rows = catalog
  .map((c) => `  { family: ${JSON.stringify(c.family)}, category: ${JSON.stringify(c.category)}, cls: ${JSON.stringify(c.cls)}, weights: [${c.weights.join(", ")}] },`)
  .join("\n");

const file = `// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// ${catalog.length} serif/sans-serif families from the Google Fonts library,
// each with a baked-in visual class and representative weights. The pairing
// engine samples from this catalog to generate novel pairings.

export const FONT_CATALOG = [
${rows}
];
`;

writeFileSync(OUT, file);
console.log(`wrote ${catalog.length} fonts to ${OUT}`);
const dist = catalog.reduce((a, c) => ((a[c.cls] = (a[c.cls] || 0) + 1), a), {});
console.log("class distribution:", JSON.stringify(dist));
